### ISSUE TITLE
verbose stack Error

### ISSUE THREAD

**Issue by super2457** [jaywcjlove/stylus-px2rem#1]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\software\\nodejs\\node.exe',
1 verbose cli   'D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info precompile stylus@1.0.0
6 info compile stylus@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info stylus@1.0.0 Failed to exec compile script
9 verbose stack Error: stylus@1.0.0 compile: `stylus -u stylus-px2rem -o ./css/main.css compiled/main.styl`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\software\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\software\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid stylus@1.0.0
11 verbose cwd D:\Code\stylus
12 error Windows_NT 6.1.7601
13 error argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error stylus@1.0.0 compile: `stylus -u stylus-px2rem -o ./css/main.css compiled/main.styl`
17 error Exit status 1
18 error Failed at the stylus@1.0.0 compile script 'stylus -u stylus-px2rem -o ./css/main.css compiled/main.styl'.
18 error This is most likely a problem with the stylus package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     stylus -u stylus-px2rem -o ./css/main.css compiled/main.styl
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs stylus
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls stylus
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by jaywcjlove** [comment]
@super2457  I don't know how you use it.
